title:        "Andrei Lisnic blog"
tagline:      "random thoughts by @andrei_lisnic"
url:          https://alisnic.github.io
author:
  name:       "Andrei Lisnic"
  email:      "andrei.lisnic@gmail.com"
markdown:     kramdown
permalink:    /posts/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
