title:        "Andrei Lisnic"
tagline:      "random thoughts by @andrei_lisnic"
url:          http://alisnic.github.io
author:
  name:       "Andrei Lisnic"
  email:      "andrei.lisnic@gmail.com"
markdown:     kramdown
permalink:    /posts/:title
